### PR TITLE
made clicking MovieTile redirect to MoviePage

### PR DESCRIPTION
**Pull request by Marcin-Malek**
I added an id prop in MovieTile because i could not pass key in props - it returned undefined.

### CODE REVIEW

**Comment by damianmichalowski** [comment]
maybe add sth like hover/ animation, in order to show user they can click on it

**Comment by Marcin-Malek** [comment]
> maybe add sth like hover/ animation, in order to show user they can click on it

Check my latest changes and let me know what you think of it

**Comment by damianmichalowski** [comment]
I tried it my self because i dont like the effect you made, pls check, and replece it in your code
```
`export const Content = styled.li`
    padding: 16px;
    background-color: ${({ theme }) => theme.color.white};
    box-shadow: 0 4px 12px rgba(186, 199, 213, 0.5);
    border-radius: 5px;
    display: flex;
    flex-direction: column;
    transition: 0.2s;
    &:hover {
        transform: scale(1.02);
        box-shadow: 0 4px 12px rgba(186, 199, 213, 0.9);
    }`
```
let me know what you think

**Comment by Marcin-Malek** [comment]
It does look a lot better. Thanks for reviewing it.

**Review by damianmichalowski — APPROVED** [review]

**Comment by damianmichalowski** [comment]
i also thing to maybe add some styling on active (some kind of flash)
such a detail but why not

**Comment by damianmichalowski** [comment]
```
&:active {
        filter: brightness(94%);
        transform: scale(1.03);
    }
```

**Review by JamieShifter — APPROVED** [review]

**Review by damianmichalowski — APPROVED** [review]
cool, great job

**Pull request merged**
