### PR TITLE
Movie page layout

### PR DESCRIPTION
**Pull request by Marcin-Malek**
I have added a poster and basic layout in MoviePages, still having some concerns about responsiveness of poster. Let me know what you think.

### CODE REVIEW

**Comment by Marcin-Malek** [comment]
[Stylowanie MoviePage](https://trello.com/c/to6OQGeV/12-stylowanie-moviepage)

**Comment by JamieShifter** [comment]
Navbar color looks disgusting compared to the blackness of the poster XD maybe we SHOULD change our theme black to #000000 hmmm

**Comment by Marcin-Malek** [comment]
> Navbar color looks disgusting compared to the blackness of the poster XD maybe we SHOULD change our theme black to #000000 hmmm

Do you have latest changes pulled? Navbar and poster shadow is the same color. Or do you mean its digsuting because it is the same color? Also i think i have resolved the white stripe issue in the poster with my last commit, take a look and let me know if it's ok.

**Review by damianmichalowski — APPROVED** [review]
1. Can you explain the use of tags dl, dd?
2. maybe do poster scale by percentages instead of consted values px ? (suggest)

**Pull request merged**
