### PR TITLE
responsive movie tile- witch example 4 tile on page 

### PR DESCRIPTION
**Pull request by damianmichalowski**

### CODE REVIEW

**Comment by damianmichalowski** [comment]
[Uzupełnić Readme](https://trello.com/c/BTb7JUov/13-uzupe%C5%82ni%C4%87-readme)

**Review by Marcin-Malek — CHANGES_REQUESTED** [review]
Great job, I like that you have already thought of animated previews. I have some concerns about technologies and methods you listed:
-Does CSS4 even exist? 
-Will we be really using BEM? I thought we wouldn't be using classNames and CSS files.
-Instead of `Redux with react-redux v8.0.2` you could just go with `React Redux v8.0.2`
-I dont think we will be using promises and async/await with redux-saga or will we?

Also i think you made changes in the wrong branch since readme has nothing to do with movie-tile but that is a minor overlook.

**Comment by JamieShifter** [comment]
> -I dont think we will be using promises and async/await with redux-saga or will we?
How else will we fetch data from api, even with redux-saga? :O

**Review by JamieShifter — APPROVED** [review]

**Comment by Marcin-Malek** [comment]
> > How else will we fetch data from api, even with redux-saga? :O

Nevermind, I was thinking about axios. I know those are promise based but then we would not need any other promises or async functions.

**Comment by damianmichalowski** [comment]
# I will respond to your inquiries.
## -Does CSS4 even exist? 
We use CSS2 version but CSS level 3, 4, CSS4 is not the official version but it is a conventional name which includes features we use
here link to CSS SPEC­I­FI­CA­TIONS:
[www.w3.org/Style/CSS/specs.en](https://www.w3.org/Style/CSS/specs.en.html)

## -Will we be really using BEM? I thought we wouldn't be using classNames and CSS files.
## -Instead of Redux with react-redux v8.0.2 you could just go with React Redux v8.0.2
i fixed that

## -I dont think we will be using promises and async/await with redux-saga or will we?
I made a template with everything we can give to redme with the thought that we will just add and remove skills
so you right i remove promises and async/await.

## Also i think you made changes in the wrong branch since readme has nothing to do with movie-tile but that is a minor overlook.
I thought not to create a new branch, but to do it on the one with a responsive tile, the next time I will split two tasks into two branches, but now it doesn't make sense to separate it

**Comment by damianmichalowski** [comment]
and we'll make some corrections and tweak the details at the end of the project i think

**Review by Marcin-Malek — APPROVED** [review]
Surely, we will make some changes in the future, but we should try to make our changes as relevant as possible in the time we make them. I get what you are saying about CSS, however there are some css modules that go up to level 6 - that does not mean we are using CSS 6. I think it is better to not specify version of CSS and HTML, since these are more like living standard now.

**Comment by damianmichalowski** [comment]
Okay so i leave CSS , HTML rather than CSS4 , HTML5

**Comment by damianmichalowski** [comment]
now i am making changes witch responsive tile and soon i give you re request pull request

**Comment by damianmichalowski** [comment]
i changed global style in my branch - added this `*,` because i couldn't work without that , when we will merge it will be easy conflict to resolve

**Review by JamieShifter — APPROVED** [review]

**Pull request merged**
