### PR TITLE
Feature/search bar

### PR DESCRIPTION
**Pull request by Marcin-Malek**
I have created, some hooks for query. Searching movies is now working and i hope it is bug free - please test and check if everything is working properly. I tried to make separate generator functions for popular movies and searched movies but it was not entirely working, i made some trials with redux-saga `race` effect but it did not work out. Let me know what you think of this solution.

### CODE REVIEW

**Comment by JamieShifter** [comment]
Please check if you have compilation warnings and address them:
image

**Comment by Marcin-Malek** [comment]
> Please check if you have compilation warnings and address them: image

I did not have any when i commited my changes.

**Review by damianmichalowski — APPROVED** [review]

**Comment by Marcin-Malek** [comment]
This should be bug free now. I made another query for search results page and joined saga functions together so it is not bugged when removing search query in a fast manner. Please review my changes once again when you are free.

**Review by JamieShifter — APPROVED** [review]
It's alive!

**Review by damianmichalowski — APPROVED** [review]
Very good changes, good job

**Pull request merged**
