### PR TITLE
Movie details

### PR DESCRIPTION
**Pull request by Marcin-Malek**
Here are changes I have made: 
- created MoviePage component and routed it to /movies/:id (To view it just now go to movies/1 or whatever number)
- created MovieDetails component with props passed from MoviePage
- added responsive design for mobile devices 
- added missing color in theme.js
- changed colors and set a global color in `<body>` according to what we discussed earlier.

I'd like to discuss with you how are we going to apply responsiveness for tablets and other devices without exact UI models in Figma.

Let me know if there is something i could improve or explain to you.

### CODE REVIEW

**Comment by Marcin-Malek** [comment]
[Kafelek MovieTitle - main info](https://trello.com/c/Sz9SShEZ/10-kafelek-movietitle-main-info)

**Review by damianmichalowski — APPROVED** [review]
I can't fault anything, everything looks great, good job, everything looks great

**Comment by Marcin-Malek** [comment]
Box-sizing was not working, I fixed it by adding asterisk selector in global style.

**Comment by JamieShifter** [comment]
Check it out:

image

^ It looks like title and all that stuff is in the second wrapper/container which has a slightly bigger padding on the bottom(92 px instead of 40px like from the top).

**Comment by Marcin-Malek** [comment]
Yes, Thanks @JamieShifter You are totally right, i have missed it. I haven't made another wrapper to resolve this issue, instead i have added another empty grid row and now it looks more like it. Let me know if you are ok with the outcome.

**Pull request merged**
